### ISSUE TITLE
Spawning helper process fails on Android when SELinux is in enforcing mode

### ISSUE THREAD

**Issue by nemicohen2** [frida/frida-core#19] opened 2015-04-29 17:38 UTC
Hi, I have an issue with Frida.
After encountering a problem with my python using UCS4, and easy_install frida using UCS2, I cloned your git and built Frida from source: both the python bindings and frida-server.
Deployed the frida-server on my phone with adb.
When trying to start frida-server -t -0 (like you showed in the example), got an error that no "-t" option was known, so I just ran it without any option: `./frida-server.`
After forwarding the ports frida-ps -R works fine, but when I do `frida-trace -R -i open com.android.chrome` I get the following error:
`Failed to attach: unexpectedly timed out while spawning helper process`

Using Ubunutu  15 and Galaxy S3 with Android 4.3
Would appreciate your help! :)

**Comment by oleavr** [comment] 2015-04-29 17:41
Thanks, great catch!

I've just done a massive refactoring in order to provide proper error messages throughout the code-base, and you seem to have found a regression not caught by the tests. I'm still working on some changes in the same area, and will let you know as soon as I get this issue fixed (should be later today hopefully).

Cheers!

**Comment by oleavr** [comment] 2015-04-29 21:08
Could you try pulling the latest master (don't forget `git submodule update`) and do a full rebuild to see if it improves the situation? PS: with the new changes in master we only use one single TCP port (27042 like before) and multiplex the sessions over it.

**Comment by oleavr** [comment] 2015-04-30 02:06
This should now be fixed, please let me know if it works for you. Thanks!

**Comment by nemicohen2** [comment] 2015-04-30 11:12
Thanks for the quick response and fix! :+1: 
I compiled everything and got the following detailed exception:
`Failed to attach: unexpected error while spawning helper process: Failed to execute child process "/data/local/tmp/.frida-a3bece4740870edf8e5a76405353f4a2/frida-helper-32" (Permission denied)`
I tried `chmod +x frida-server`, but still got the same exception.
I tried running `sudo ./frida-trace -R -i open com.android.chrome` and got a different exception:
`Failed to attach: exception has been thrown` 
But it makes no sense running this command with `sudo` as the permission problem was reported on my Android.

(I ran the server with root permissions, obviously)

Thanks in advance!

**Comment by oleavr** [comment] 2015-04-30 11:22
Aha, very interesting. Thanks for testing! So it looks like this doesn't work:
https://github.com/frida/frida-core/blob/60cb7b15767cb9ad9b0f664826d7b84fab4c3609/src/linux/frida-helper-process.vala#L303
We basically write out a temporary file with our helper executable, chmod it, and then try to run it. Running it reports "Permission denied", which makes me think that the chmod didn't work. Could you check what kind of permissions are actually set on the frida-helper-32 executable just after it fails? (`/data/local/tmp/.frida-a3bece4740870edf8e5a76405353f4a2/frida-helper-32` in the above case).

**Comment by nemicohen2** [comment] 2015-04-30 11:29
`root@m0:/data/local/tmp # ls -l                                                
-rwxrwxrwx shell    shell    24290772 2015-04-30 13:38 frida-server
-rwxrwxrwx root     root        65536 2015-04-21 09:00 wssdmdatabase.db`
Right after it fails. No file is ever here :(

**Comment by oleavr** [comment] 2015-04-30 11:31
It's in a hidden directory; does "ls -la" give you anything?

**Comment by nemicohen2** [comment] 2015-04-30 11:35
Thousands of temporary frida files! I deleted them all and ran the command again, and got this:
`Failed to attach: error creating FIFO with mkfifo: No such file or directory`

**Comment by oleavr** [comment] 2015-04-30 11:39
Hmm. Did you restart the frida-server after doing that cleaning? Btw, does your devices have any kind of security software out of the ordinary from stock Android?

**Comment by nemicohen2** [comment] 2015-04-30 11:42
Nope, it's a stock Android.
Restarting the server gave me the permissions error again, and here is the new temp file:
`drwxr-xr-x root     root              2015-04-30 14:39 .frida-0452706d864027dad2100f9b3dd5d44a`
Looks like everyone got execute permissions.
I tried `chmod 777 .frida-0452706d864027dad2100f9b3dd5d44a`, and now the frida-trace gives me `Failed to attach: exception has been thrown` again.

**Comment by oleavr** [comment] 2015-04-30 11:48
Hmm. Could you look inside that .frida-* directory to see what the permissions of the frida-helper-32 binary are?

**Comment by nemicohen2** [comment] 2015-04-30 11:50
Oh, my bad.
`-rwxr-xr-x root     root     10336892 2015-04-30 14:41 frida-agent-32.so`
`-rwx------ root     root      2517272 2015-04-30 14:41 frida-helper-32`
You were right. I cannot change the permissions on it, as I need to restart the server, which creates a new random hidden temp folder.

**Comment by oleavr** [comment] 2015-04-30 14:27
Hmm, it's really odd that it fails to spawn with those permissions. Let me improve the code a bit so it'll retry if it fails to spawn and you try again later (that way you can tweak the permissions to check what works). I'll let you know when it's pushed.

**Comment by oleavr** [comment] 2015-04-30 14:33
Ooh.. I wonder if the filesystem containing /data/local/tmp might be MNT_NOEXEC; could you please check?

**Comment by nemicohen2** [comment] 2015-04-30 14:55
I changed the permissions on frida/frida-core/src/linux/frida-helper-process.vala#L303 to be 777 and re-compiled everything - that didn't work sadly.
I'm a bit of a starter with android, how do I check if the file system is mnt_noexec?
I couldn't find it on `mount` command...

**Comment by oleavr** [comment] 2015-04-30 23:39
Try:
`cat /proc/mounts`

I'm fairly certain that this is the issue (can't see any other reason why), so tomorrow I'll have a look at improving the implementation to pick a better location.

**Comment by oleavr** [comment] 2015-05-02 17:57
Would be great if you could give the latest master a try from a clean git clone. Thanks!

**Comment by nemicohen2** [comment] 2015-05-03 08:29
Thanks for all the quick fixes!
I gave it another try but got the same permission error.
I checked back with my Android, and it seems the server still made the .frida-X directory in `/data/local/tmp`
I looked at your commit, and it seems you changed it to be made in `/proc/self/exec` directory link.
Since I am currently running frida-server from `/data/local/tmp` (As seen in your examples), `/proc/self/exec` points at `/data/local/tmp`, so really nothing has changed...

P.S: I changed your source to give the temporary directory permissions to 777. It didn't work as well :(

P.S.S: Running `cat /proc/mounts` nothing had NO_EXEC...

**Comment by oleavr** [comment] 2015-05-03 12:05
Thanks for testing! I forgot to tell you that my change, which will be documented on the website for the next release, requires that you deploy frida-server somewhere suitable on your device, where:
- the filesystem is not mounted with the `noexec` option
- every directory leading up to this directory is world readable and executable
Could you check if any of the filesystems in /proc/mounts has the `noexec` option set? (Sorry, I gave you the name of the flag used in the API, and not the name used by the /proc entry and mount utility.)

**Comment by oleavr** [comment] 2015-05-03 12:18
Also, if you deployed it to /data/local/tmp then that invalidates that `noexec` theory, because you were able to execute `frida-server` there.

**Comment by oleavr** [comment] 2015-05-03 12:18
What happens if you try to execute frida-helper-32 by hand?

**Comment by nemicohen2** [comment] 2015-05-03 12:29
Nothing in proc/mounts has `noexec`.
I can execute frida-helper-32 without any problem. (But only when I'm root by using adb shell and then running `su`).
I had thought that frida-server tries to run frida-helper-32 with lower permissions, but as I said even when I ran it after compiling with 777 permissions it failed, displaying the same error.

**Comment by oleavr** [comment] 2015-05-03 12:47
Aha. That's interesting. Here's the code Frida implicitly calls to spawn the process (GSubprocess calls GSpawn): https://github.com/frida/glib/blob/398c7b88c534e350a3f18d0c47b9f8fe909f9d9e/glib/gspawn.c#L1293

No setuid/setgid calls, so if you execute frida-server as root I can't see any reason it would drop privileges, but there must be something we're missing here.

What happens if you try the failed operation twice? (The code will now retry spawning the helper even if it already failed before.)

**Comment by nemicohen2** [comment] 2015-05-03 17:26
I got the same error...
After Googling a bit about the error generally on Unix, I tried moving frida-server around.
And wherever I put it, it kept spawning the frida-helper at /data/local/tmp. Why would that happen?

**Comment by oleavr** [comment] 2015-05-03 20:00
Sounds like you might want to do "make clean" and then build just "make server-android" (do not build anything else first, as the Vala code is only generated once and that #if ANDROID check will be evaluated at that point).

**Comment by nemicohen2** [comment] 2015-05-04 16:53
Okay, now it spawns it wherever I put the frida-server, but I still get the same error. :(
What do?

**Comment by nemicohen2** [comment] 2015-05-07 11:59
Is there anything I can do to make it work? I really want to use Frida!

**Comment by oleavr** [comment] 2015-05-07 12:03
Sorry for the late follow-up here, I've been swamped lately. I will try to find some time soon. Feel free to dig a bit in the meantime if you feel like stepping around with a debugger or adding debug printouts strategically.

**Comment by chaudhryfaisal** [comment] 2015-05-22 04:23
I am getting same thing, is there a solution?

Failed to attach: unexpected error while spawning helper process: Failed to execute child process "/data/local/tmp/.frida-9eea4e936ccad56ffdecc4527ea3
88f2/frida-helper-32" (Permission denied)


ls -la
drwxrwxrwx shell    shell             2015-05-21 23:16 tmp
root@android:/data/local # cd tmp
cd tmp
root@android:/data/local/tmp # ls -la
ls -la
drwxrwxrwx root     root              2015-05-21 23:20 .frida-9eea4e936ccad56ffdecc4527ea388f2
-rwxrwxrwx shell    shell    15558928 2015-05-21 22:45 frida-server
root@android:/data/local/tmp # cd .frida*
cd .frida*
root@android:/data/local/tmp/.frida-9eea4e936ccad56ffdecc4527ea388f2 # ls -la
ls -la
-rwxrwxrwx root     root     10324520 2015-05-21 23:16 frida-agent-32.so
-rwxrwxrwx root     root      2513148 2015-05-21 23:16 frida-helper-32


when I manually execute process frida-helper-32 I dont get any errors, but running through frida-trace or frida-discover I get that error

**Comment by oleavr** [comment] 2015-05-22 11:32
I've been digging further into this and it turns out this is caused by the device' kernel having SELinux enabled in enforcing mode. We do not yet integrate with SELinux, but I'm working on fixing that. In the meantime you could look into switching SELinux into permissive mode.

**Comment by pavel-lazar** [comment] 2015-05-28 19:44
Hey, 
I had the same problem with my rooted Samsung s4 and I came across this thread. 
While trying to solve the issue I have set SELinux into permissive mode and disabled KNOX with no success. 
After some digging in Samsung's Kernel modifications I think I have found the root cause of the problem. 
As you can see in https://github.com/gokulnatha/GT-I9500/blob/master/arch/arm/kernel/sys_arm.c#L175 they have a restriction on the fork syscall that makes it fail if the source executable is from the /data partition. 
I am not very familiar with Frida's source code so I do not know what is the best solution but I think that calling /system/bin/sh should work.

Hope it will help you solve the issue! 

Thanks for the great work on Frida.

**Comment by oleavr** [comment] 2015-05-30 21:41
@pavel-lazar, awesome research, thanks a lot! I'm going to eliminate the need to spawn the helper process under normal circumstances, by making the Linux injector capable of injecting into both 32- and 64-bit processes (we currently use a 32-bit helper to inject into 32-bit processes, and a 64-bit helper to inject into 64-bit ones).

**Comment by oleavr** [comment] 2015-08-11 14:53
The Samsung part of this issue is now resolved:
https://github.com/frida/frida-core/commit/cf1a279e4517fc2551a99c01510c752c72a22b82
(Requires SuperSU to be installed on such devices.)

**Comment by oleavr** [comment] 2015-08-15 10:24
Fixed in latest git master. We also support ART and 64-bit ARM devices now!

**Closed by oleavr** 2015-08-15 10:24 UTC

**Comment by christiancoleman** [comment] 2017-08-18 23:12
@oleavr  Hate to bump an old thread but I appear to be having this exact issue on a Note 5. I see the fix is to use SuperSU, but do you know if there is a way to use Magisk's root rather that SuperSU and still get it working? I can install both SuperSU and Magisk but SuperSU prevents apps that rely on Google's SafetNet to work.

**Comment by strlbs** [comment] 2017-08-19 07:46
Hi all,

Sorry to be a pain, I'm new to frida and I have a Samsung Galaxy 6 Edge also rooted with Magisk and I'm having the same issue. However, the error is different with frida-trace and appmon.

> $ frida-trace -R -i open "com.MyTest.android"
> Attaching...                                                            
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/Library/Python/2.7/site-packages/frida/application.py", line 411, in _run
>     work()
>   File "/Library/Python/2.7/site-packages/frida/application.py", line 266, in _try_start
>     self._update_status("Failed to attach: %s" % e)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)


> $ python appmon.py -a "com.MyTest.android" -p android --spawn 0
> 
>      ___      .______   .______   .___  ___.   ______   .__   __. 
>     /   \     |   _  \  |   _  \  |   \/   |  /  __  \  |  \ |  | 
>    /  ^  \    |  |_)  | |  |_)  | |  \  /  | |  |  |  | |   \|  | 
>   /  /_\  \   |   ___/  |   ___/  |  |\/|  | |  |  |  | |  . `  | 
>  /  _____  \  |  |      |  |      |  |  |  | |  `--'  | |  |\   | 
> /__/     \__\ | _|      | _|      |__|  |__|  \______/  |__| \__| 
>                         github.com/dpnishant
>                                                                   
> 
> [ERROR] failed to execute child process “/data/local/tmp/re.frida.server/frida-helper-32” (Permission denied)
> Traceback (most recent call last):
>   File "appmon.py", line 317, in init_session
>     session = device.attach(app_name)
>   File "/Library/Python/2.7/site-packages/frida/core.py", line 97, in attach
>     return Session(self._impl.attach(self._pid_of(target)))
> PermissionDeniedError: failed to execute child process “/data/local/tmp/re.frida.server/frida-helper-32” (Permission denied)
> ^CTraceback (most recent call last):
>   File "appmon.py", line 358, in <module>
>     script.unload()
> NameError: name 'script' is not defined

I was unsure about the arch, since it tries to load the 32 bits I tried install frida-server 32 bits and what called my attention is that appmon shows different errors to spawn a process or attach to it.

`$ python appmon.py -a "com.MyTest.android" -p android --spawn 0

     ___      .______   .______   .___  ___.   ______   .__   __. 
    /   \     |   _  \  |   _  \  |   \/   |  /  __  \  |  \ |  | 
   /  ^  \    |  |_)  | |  |_)  | |  \  /  | |  |  |  | |   \|  | 
  /  /_\  \   |   ___/  |   ___/  |  |\/|  | |  |  |  | |  . `  | 
 /  _____  \  |  |      |  |      |  |  |  | |  `--'  | |  |\   | 
/__/     \__\ | _|      | _|      |__|  |__|  \______/  |__| \__| 
                        github.com/dpnishant
                                                                  

[INFO] Attached to com.MyTest.android
[INFO] Building injection...
[INFO] Instrumentation started...
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [18/Aug/2017 23:51:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Aug/2017 23:51:19] "GET /static/img/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [18/Aug/2017 23:51:30] "GET /monitor?app= HTTP/1.1" 301 -
127.0.0.1 - - [18/Aug/2017 23:51:30] "GET /monitor/?app= HTTP/1.1" 200 -
127.0.0.1 - - [18/Aug/2017 23:51:30] "GET /static/img/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [18/Aug/2017 23:51:30] "GET /static/img/to-top.png HTTP/1.1" 304 -
127.0.0.1 - - [18/Aug/2017 23:51:30] "GET /static/img/to-bottom.png HTTP/1.1" 304 -
[2017-08-18 23:51:30,492] ERROR in app: Exception on /api/fetch [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appmon.py", line 59, in serve_json
    response = db.read_from_database(db_name, index)
  File "/Users/strlbs/Downloads/MyTest/appmon/database/__init__.py", line 50, in read_from_database
    db = dataset.connect('sqlite:///./app_dumps/%s.db' % (db_path))
  File "/Library/Python/2.7/site-packages/dataset/__init__.py", line 42, in connect
    ensure_schema=ensure_schema, row_type=row_type)
  File "/Library/Python/2.7/site-packages/dataset/persistence/database.py", line 62, in __init__
    self.metadata.reflect(self.engine, views=reflect_views)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/schema.py", line 3855, in reflect
    with bind.connect() as conn:
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 2091, in connect
    return self._connection_cls(self, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 2177, in raw_connection
    self.pool.unique_connection, _connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 1292, in _do_get
    return self.connection
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/langhelpers.py", line 764, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 1264, in connection
    return _ConnectionRecord(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
OperationalError: (sqlite3.OperationalError) unable to open database file
127.0.0.1 - - [18/Aug/2017 23:51:30] "GET /api/fetch?id=0&app=&_=1503111090415 HTTP/1.1" 500 -
[WARNING] "com.MyTest.android" has terminated!
^C^CTraceback (most recent call last):
  File "appmon.py", line 358, in <module>
    script.unload()
  File "/Library/Python/2.7/site-packages/frida/core.py", line 303, in unload
    self._impl.unload()
frida.InvalidOperationError: script is destroyed
`

`$ python appmon.py -a "com.MyTest.android" -p android --spawn 1

     ___      .______   .______   .___  ___.   ______   .__   __. 
    /   \     |   _  \  |   _  \  |   \/   |  /  __  \  |  \ |  | 
   /  ^  \    |  |_)  | |  |_)  | |  \  /  | |  |  |  | |   \|  | 
  /  /_\  \   |   ___/  |   ___/  |  |\/|  | |  |  |  | |  . `  | 
 /  _____  \  |  |      |  |      |  |  |  | |  `--'  | |  |\   | 
/__/     \__\ | _|      | _|      |__|  |__|  \______/  |__| \__| 
                        github.com/dpnishant
                                                                  

Now Spawning com.MyTest.android
[ERROR] unable to handle 64-bit processes due to build configuration
Traceback (most recent call last):
  File "appmon.py", line 301, in init_session
    pid = device.spawn([app_name])
  File "/Library/Python/2.7/site-packages/frida/core.py", line 85, in spawn
    return self._impl.spawn(argv)
NotSupportedError: unable to handle 64-bit processes due to build configuration
^CTraceback (most recent call last):
  File "appmon.py", line 358, in <module>
    script.unload()
NameError: name 'script' is not defined
`
Looking for the error I found a Chinese post that lead to no answer, anyway I found a script that automatiza the process and confirms my arch is 64 bits, so not sure about the reason that it's calling the 32 bits helper.

`$ python3 frida-server-start 
	[+] Found following device:
	03157dfc2370a53f       device usb:337641472X product:zeroltedv model:SM_G925I device:zerolte
[*] Current installed Frida version: 10.4.0
[*] Trying to determine device's arch.
	[+] Found arch: arm64
	[+] Downloading: https://github.com/frida/frida/releases/download/10.4.0/frida-server-10.4.0-android-arm64.xz
	[+] Writing file as: frida-server-10.4.0-android-arm64.
frida-server-10.4.0-android-arm64: 1 file pushed. 6.8 MB/s (39330040 bytes in 5.528s)
	[+] File pushed to device successfully.
	[+] Executing frida-server on device.
	[+] Fetching the PID of frida-server and saving it to file.
root@zerolte:/ #  
`

If I try to call the helper from shell (with root privileges) it return the message below.

`data/local/tmp/re.frida.server/frida-helper-32                                <

(process:19084): Frida-CRITICAL **: frida_helper_service_construct: assertion 'parent_address != NULL' failed

(process:19084): Frida-CRITICAL **: frida_helper_service_run: assertion 'self != NULL' failed
root@zerolte:/data/local/tmp # 
root@zerolte:/data/local/tmp # 
data/local/tmp/re.frida.server/frida-helper-6                                 <
sh: /data/local/tmp/re.frida.server/frida-helper-6: not found
data/local/tmp/re.frida.server/frida-helper-64                                <

(process:19113): Frida-CRITICAL **: frida_helper_service_construct: assertion 'parent_address != NULL' failed

(process:19113): Frida-CRITICAL **: frida_helper_service_run: assertion 'self != NULL' failed
root@zerolte:/data/local/tmp # 
`

BTW, I also use Magisk because SuperSu will break SafetyNet :)

Anything else that I could provide to try help?

Thanks.

**Comment by rocketrobot99** [comment] 2017-09-13 07:04
@oleavr I too am really interested in using Frida, however, I get the same problem because I am using Magisk rather than SuperSU. Is there a work around?

**Comment by oleavr** [comment] 2017-09-13 11:34
@christiancoleman I would suggest figuring out Magisk's API, just like I did for SuperSU, and implementing a client for it.

**Comment by rocketrobot99** [comment] 2017-09-13 11:36
Actually, you can get it to work if use copy the frida-server to a directory other than /data. e.g /system/priv-
app/frida
